# Numpy

Numpy is a low level library written in c and FORTRAN for high level mathematical functions.Numpy cleaverlly overcome the problem of running slower algorithms on python by using multidimensional arrays and functions that operate on arrays.

## 1 creating numpy arrays 

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5]) #one dimensional arry

In [3]:
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #two dimensional array

In [7]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
type(arr2)

numpy.ndarray

In [9]:
arr3=np.zeros((2,3))

In [10]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4=np.ones((3,3))

In [12]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr5=np.identity(5)

In [14]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr6=np.arange(10)

In [16]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

What is the difference between arange and range function?
Ans:Range() function is used to generate list in a given range.
    arange() function is used to generate array in a given range.